CREATE TABLE venues (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL UNIQUE,
    city VARCHAR(120),
    max_cap INTEGER NOT NULL
);

CREATE TABLE events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    event_date DATE NOT NULL,
    description VARCHAR(500) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    venue_id INTEGER NOT NULL,
    CONSTRAINT fk_events_venue
        FOREIGN KEY (venue_id) REFERENCES venues (id)
);

CREATE INDEX idx_events_event_date ON events (event_date DESC);
CREATE INDEX idx_events_venue_id ON events (venue_id);
