ALTER TABLE venues
    ADD COLUMN IF NOT EXISTS city VARCHAR(120);

UPDATE venues
SET city = 'Bogota'
WHERE city IS NULL;

ALTER TABLE venues
    ALTER COLUMN city SET NOT NULL;

CREATE TABLE categories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL UNIQUE,
    description VARCHAR(255) NOT NULL
);

CREATE TABLE events_categories (
    event_id INTEGER NOT NULL,
    category_id INTEGER NOT NULL,
    CONSTRAINT pk_events_categories PRIMARY KEY (event_id, category_id),
    CONSTRAINT fk_events_categories_event
        FOREIGN KEY (event_id) REFERENCES events (id) ON DELETE CASCADE,
    CONSTRAINT fk_events_categories_category
        FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE CASCADE
);

CREATE INDEX idx_events_categories_category_id ON events_categories (category_id);
